### ISSUE TITLE
Can't load world with mod enabled

### ISSUE THREAD

**Issue by InsaanNotFound** [nok-ko/bedrock-breaking#2]
Trying to load or create a world results in this. (Latest version of gobber mod and no more gems mod installed)

```
[13:26:53] [main/ERROR]: Couldn't load item tag fabric:pickaxes_diamond_level as it is missing following references: more_gems:carbonado_pickaxe (from Gobber2),more_gems:carbonado_hammer (from Gobber2),more_gems:carbonado_paxel (from Gobber2)
[13:26:53] [main/ERROR]: Couldn't load item tag curios:belt as it is missing following references: gobber2:gobber2_medallion_dolphin (from Gobber2)
[13:26:53] [main/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: java.lang.IllegalArgumentException: Unknown condition minecraft:type!
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1959) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1808) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1748) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.start(TitleScreen:5655) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.md1d6975$lambda$drawMenuButton$3$3(TitleScreen:5619) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33) ~[?:?]
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget:149) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen:296) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:92) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:162) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:162) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:127) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1071) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: com.google.gson.JsonParseException: java.lang.IllegalArgumentException: Unknown condition minecraft:type!
	at io.github.ytg1234.recipeconditions.api.condition.SingleCondition.fromJson(SingleCondition.java:91) ~[97748b2a-a43a-475e-8a42-6b03bac1f516.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.EveryCondition.fromJson(EveryCondition.java:35) ~[97748b2a-a43a-475e-8a42-6b03bac1f516.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.AnyCondition.fromJson(AnyCondition.java:40) ~[97748b2a-a43a-475e-8a42-6b03bac1f516.jar:?]
	at net.minecraft.recipe.RecipeManager.handler$dnl000$processConditions(RecipeManager:4541) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958) ~[?:?]
	... 37 more
Caused by: java.lang.IllegalArgumentException: Unknown condition minecraft:type!
	at io.github.ytg1234.recipeconditions.api.condition.SingleCondition.fromJson(SingleCondition.java:91) ~[97748b2a-a43a-475e-8a42-6b03bac1f516.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.EveryCondition.fromJson(EveryCondition.java:35) ~[97748b2a-a43a-475e-8a42-6b03bac1f516.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.AnyCondition.fromJson(AnyCondition.java:40) ~[97748b2a-a43a-475e-8a42-6b03bac1f516.jar:?]
	at net.minecraft.recipe.RecipeManager.handler$dnl000$processConditions(RecipeManager:4541) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958) ~[?:?]
	... 37 more
```

**Comment by nok-ko** [comment]
Hm, I don't really have enough information to resolve this issue. My mod's package doesn't actually show up in that stack trace, are you sure it's Bedrock Breaking that's causing the crash? Also, please send your config and mod list.

**Comment by nok-ko** [comment]
I suspect the mod `recipeconditions` is causing the problem. Check in with that mod's developer?

**Comment by YTG1234** [comment]
Hello, I am the developer of recipe conditions. Could you try [this version](https://modrinth.com/mod/recipe-conditions/version/RoUTNjhw)? @InsaanNotFound

**Comment by InsaanNotFound** [comment]
I just woke up, I will test it as soon as I get on pc.
Also, yes, error occurs when adding Bedrock Breaking to the modpack, though as you all have noticed, bug seems very weird. If it wont work, I will send you a list of all my mods (~230) + config folder

**Comment by YTG1234** [comment]
I've changed a few things regarding errors in the new version, so if it still doesn't work send the error as well.

**Comment by InsaanNotFound** [comment]
Bedrock Breaking works finally, though Recipe Conditions does the same thing again, but with every single version of Charm mod >2.1.6
```
[12:42:08] [main/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Failed to load recipe charm:atlas/atlas!
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1959) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1808) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1748) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.start(TitleScreen:5655) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mdccb8e4$lambda$drawMenuButton$3$3(TitleScreen:5619) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33) ~[?:?]
	at net.minecraft.client.gui.widget.AbstractPressableButtonWidget.onClick(AbstractPressableButtonWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget:149) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen:296) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:92) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:162) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:162) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:102) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:308) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: com.google.gson.JsonParseException: Failed to load recipe charm:atlas/atlas!
	at net.minecraft.recipe.RecipeManager.handler$dok000$processConditions(RecipeManager:4548) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958) ~[?:?]
	... 38 more
Caused by: com.google.gson.JsonParseException: java.lang.IllegalArgumentException: Unknown condition minecraft:type!
	at io.github.ytg1234.recipeconditions.api.condition.SingleCondition.fromJson(SingleCondition.java:91) ~[fabric-recipe-conditions-0.3.1.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.EveryCondition.fromJson(EveryCondition.java:35) ~[fabric-recipe-conditions-0.3.1.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.AnyCondition.fromJson(AnyCondition.java:40) ~[fabric-recipe-conditions-0.3.1.jar:?]
	at net.minecraft.recipe.RecipeManager.handler$dok000$processConditions(RecipeManager:4542) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958) ~[?:?]
	... 38 more
Caused by: java.lang.IllegalArgumentException: Unknown condition minecraft:type!
	at io.github.ytg1234.recipeconditions.api.condition.SingleCondition.fromJson(SingleCondition.java:91) ~[fabric-recipe-conditions-0.3.1.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.EveryCondition.fromJson(EveryCondition.java:35) ~[fabric-recipe-conditions-0.3.1.jar:?]
	at io.github.ytg1234.recipeconditions.api.condition.AnyCondition.fromJson(AnyCondition.java:40) ~[fabric-recipe-conditions-0.3.1.jar:?]
	at net.minecraft.recipe.RecipeManager.handler$dok000$processConditions(RecipeManager:4542) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18790(SinglePreparationResourceReloadListener:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:1958) ~[?:?]
	... 38 more
```

**Comment by InsaanNotFound** [comment]
Also, we can move this issue to repo of Recipe conditions, as issues with Bedrock Breaking have been resolved. For now. Closing as fixed.

**Comment by YTG1234** [comment]
yes, move this issue to recipe conditions.

**Comment by YTG1234** [comment]
I've figured out the cause - I'd like it to be on my repo though.
